apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}
  labels:
    app: {{ template "cp-kafka-connect.name" . }}
    chart: {{ template "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/basic-auth
stringData:
  username: {{.Values.secrets.username}}
  password: {{.Values.secrets.password}}
  #{{- range $key, $value := .Values.secrets }}
  #{{ $key }}: {{ $value | b64enc }}
  #{{- end }}