apiVersion: v1
kind: Service
metadata:
  name: {{ include "client.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{ .Values.components }} 
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}