apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  type: {{ .Values.service.type }}
  selector:
    component: {{ .Values.components }} 
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}