{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "flow-utils.serviceAccountName" . }}-clusterrole
  namespace: default
rules:
- apiGroups: ["apiextensions.k8s.io"] # "" indicates the core API group
  resources: ["customresourcedefinitions"]
  verbs: ["list"]

{{- end }}
