apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.flowJob.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flow-utils.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}