{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "flow-utils.serviceAccountName" . }}-role
  namespace: default
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "create", "list"]

- apiGroups: ["flinkoperator.k8s.io"] # "" indicates the core API group
  resources: ["flinkclusters"]
  verbs: ["create", "delete"]

{{- end }}
