{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flow-utils.serviceAccountName" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "flow-utils.serviceAccountName" . }}
    namespace: default
roleRef:
  kind: Role
  name: {{ include "flow-utils.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
