apiVersion: v1
kind: Service
metadata:
  name: {{ include "flow-utils.fullname" . }}
  labels:
    {{- include "flow-utils.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.flowServer.service.port }}
      targetPort: {{ .Values.flowServer.service.targetPort }}
      protocol: TCP
      name: flow-server-grpc
      {{- if hasKey .Values.flowServer.service "nodePort" }}
      {{- end }}
  selector:
    {{- include "flow-utils.selectorLabels" . | nindent 4 }}
