apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy: 
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
      component: {{.Values.components}}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
        component: {{.Values.components}}   
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      volumes:
        - name: {{.Values.volumes.name}}
          persistentVolumeClaim:
            claimName: {{.Values.volumes.claimname}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4010
          volumeMounts:
            - name: {{.Values.volumes.name}}
              mountPath: /usr/images
          env:
            - name: FILE_PATH
              value: {{.Values.env.file_path}}
            - name: PRISMA_URL
              value: {{.Values.env.prisma_url}}
            - name: API_HOST_73
              value: http://{{.Release.Name}}-kafkaadmin:80/kafkaadmin
            - name: API_HOST_74
              value: http://{{.Release.Name}}-eventview:80/eventview
            - name: API_HOST_77
              value: http://{{.Release.Name}}-jobserver:80/jobserver
            - name: API_HOST_78
              value: http://{{.Release.Name}}-queryconsumeroffsets:80/queryconsumeroffsets
            - name: KAFKA_CONNECT_URL
              value: http://{{.Release.Name}}-cp-kafka-connect:8083/
            - name: SCHEMA_REGISTRY_URL
              value: http://{{ .Release.Name}}-cp-schema-registry:8081/
            - name: KAFKA_REST_PROXY_URL
              value: http://cp-kafka-rest-external:8082/
            - name: GRPC_FLOW_URL
              value: {{ .Release.Name }}-flow-utils:8080
            - name: GRPC_VALIDATION_URL
              value: {{ .Release.Name }}-flow-validator:80
            - name: AKKA_HTTP_SERVER
              value: http://{{ .Release.Name }}-profile-metrics-api:9001/queryMetrics
            - name: KEYCLOAK_URL
              value: {{.Values.env.keycloak_url}}
            - name: DATABASE_URL
              value: {{.Values.env.database_url}}
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-user-pass
                  key: {{.Values.env.keycloak_user_name}}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: keycloak-user-pass
                  key: {{.Values.env.keycloak_user_pass}}

  
      
