apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4015
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}
    component: {{.Values.components}}