flow-utils:
  replicaCount: 1
  image:
    repository: prohankumar/flow-utils
    tag: "6"
  jarBuildingJob:
    image: prohankumar/flow_utils_jar_building:1
  kafka:
    external: false
    address: ""
  schemaRegistry:
    external: false
    address: ""
  flowJob:
    image: prohankumar/flow:8
    serviceAccountName: flow-sa
    namespace: default
    flinkBucket: s3p://izac-flink
    flowConfigs: '{  "kafkaConfigs": {    "kafkaSourceConfigs": {      "consumerProperties": {        "security.protocol": "SASL_SSL",        "sasl.mechanism": "PLAIN",        "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://stardevelopment.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=29kpe6kUmrl31MwhXh6Ma1KXv6439wpO8BxFZ+Ge9rk=\";"      }    },    "kafkaSinkConfigs": {      "producerProperties": {        "security.protocol": "SASL_SSL",        "sasl.mechanism": "PLAIN",        "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://stardevelopment.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=29kpe6kUmrl31MwhXh6Ma1KXv6439wpO8BxFZ+Ge9rk=\";"      },      "deliveryGuarantee": "AT_LEAST_ONCE"    }  },  "flinkProperties": {    "fs.azure.account.key.kubernetesdev.blob.core.windows.net": "A6JE1Z1K2a6Mrmuo5ZtK1KNj2CWw731iAg7F+K8HAnK8JznePVljA+DJQVRxaY2yeirS5LVqN/T7OQR1Zy/dtg=="  }}'
    stateStore:
      endpoint: http://10.10.10.33:32727
      accessKey: minio
      secretKey: minio123
  flowServer:
    containerName: flow-server
    args: ["com.whiteklay.flow.flink.FlowRequestServer"]
    service:
      port: 8080
      targetPort: 50051
  flowRequestProcessor:
    containerName: flow-request-processor
    args: ["com.whiteklay.flow.flink.FlowRequestProcessor"]
  flowFlinkJobSubmitter:
    containerName: flow-flink-job-submitter
    args: ["com.whiteklay.flow.flink.SubmitFlowJob"]
  


flow-validator:
  replicaCount: 1
  image:
    repository: prohankumar/flow-validator
    tag: "1"
  kafkaBrokers: ""
  schemaRegistry: ""
  flowConfigs: '{  "kafkaConfigs": {    "kafkaSourceConfigs": {      "consumerProperties": {        "security.protocol": "SASL_SSL",        "sasl.mechanism": "PLAIN",        "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://stardevelopment.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=29kpe6kUmrl31MwhXh6Ma1KXv6439wpO8BxFZ+Ge9rk=\";"      }    },    "kafkaSinkConfigs": {      "producerProperties": {        "security.protocol": "SASL_SSL",        "sasl.mechanism": "PLAIN",        "sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://stardevelopment.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=29kpe6kUmrl31MwhXh6Ma1KXv6439wpO8BxFZ+Ge9rk=\";"      },      "deliveryGuarantee": "AT_LEAST_ONCE"    }  },  "flinkProperties": {    "fs.azure.account.key.kubernetesdev.blob.core.windows.net": "A6JE1Z1K2a6Mrmuo5ZtK1KNj2CWw731iAg7F+K8HAnK8JznePVljA+DJQVRxaY2yeirS5LVqN/T7OQR1Zy/dtg=="  }}'
  service:
    type: ClusterIP
    port: 80
    targetPort: 50051


profile-kafka-to-postgres:
  image:
    repository: ytrg10/kafka-to-postgres
    tag: latest
  envVariables:
    postgresServer: izac-postgresql-headless:5432
    database: profilemetrics
    username: postgres
    password: postgrespwd
    table: metrics
    outputTopic: profile-test-1
    sr_url: http://izac-cp-schema-registry:8081
    kafka_broker: stardevelopment.servicebus.windows.net:9093
    groupId: profile-kafka-to-postgres


profile-metrics-api:
  image:
    repository: ytrg10/profile_metrics_api
    tag: 1.0.0
  envVariables:
    postgresServer: izac-postgresql-headless:5432
    database: profilemetrics
    username: postgres
    password: postgrespwd
    table: metrics
